name: iOS Build and Release

on:
  push:
    tags:  
      # Push events to every tag starting with "sdk", including those with /     
      - 'sdk**'
  pull_request:
    branches:
      - 'master'

jobs:
    build_ios:
        name: Build Android+iOS Frameworks
        runs-on: macos-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Install nightly toolchain
              uses: dtolnay/rust-toolchain@nightly
            - name: Build iOS Framework
              run: |
                rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
                make generate_xcframework
            - name: Move and zip Framework
              run: |
                mv target/URRegistryFFI.xcframework URRegistryFFI.xcframework
                zip -r URRegistryFFI.xcframework.zip URRegistryFFI.xcframework
                echo "XCFramework Checksum: $(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)"
                XCF_CHECKSUM=$(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)
                echo "XCFramework Checksum: $XCF_CHECKSUM" >> $GITHUB_STEP_SUMMARY
            - name: Attach artifact
              uses: actions/upload-artifact@v3
              with:
                name: URRegistryFFI.xcframework.zip
                path: URRegistryFFI.xcframework.zip
            - name: Upload XCFramework to Release
              if: github.ref_type == 'tag'
              uses: svenstaro/upload-release-action@2.5.0
              with:
                file: URRegistryFFI.xcframework.zip
                asset_name: URRegistryFFI.xcframework.zip
                tag: ${{ github.event.base_ref }}
                overwrite: true
                make_latest: false
                body: "iOS XCFramework Checksum: $(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)"
        
