name: Build and Release

on:
  push:
    tags:  
      # Push events to every tag not containing /      
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
    build_all:
        name: Build Android+iOS Frameworks
        runs-on: macos-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Install nightly toolchain
              uses: dtolnay/rust-toolchain@nightly
            - name: Setup NDK
              uses: nttld/setup-ndk@v1
              with:
                ndk-version: r25b
            - name: Build Android
              run: |
                cargo install cargo-ndk
                rustup target add aarch64-linux-android
                rustup target add armv7-linux-androideabi
                rustup target add i686-linux-android
                rustup target add x86_64-linux-android
                make android
            - name: Build iOS
              run: |
                rustup target add aarch64-apple-ios
                rustup target add x86_64-apple-ios
                rustup target add aarch64-apple-ios-sim
                make generate_xcframework
            - name: Move and zip iOS + Android
              run: |
                mv target/release android-release
                zip -r android-release.zip android-release
                mv target/URRegistryFFI.xcframework URRegistryFFI.xcframework
                zip -r URRegistryFFI.xcframework.zip URRegistryFFI.xcframework
                echo "XCFramework Checksum: $(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)"
                XCF_CHECKSUM=$(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)
                echo "XCFramework Checksum: $XCF_CHECKSUM" >> $GITHUB_STEP_SUMMARY
            - name: Attach Android artifact
              uses: actions/upload-artifact@v3
              with:
                name: android-release.zip
                path: android-release.zip
            - name: Upload Android Framework to Release
              if: github.ref_type == 'tag'
              uses: svenstaro/upload-release-action@2.5.0
              with:
                file: android-release.zip
                asset_name: android-release.zip
                tag: ${{ github.event.base_ref }}
                overwrite: true
                make_latest: false
            - name: Attach iOS artifact
              uses: actions/upload-artifact@v3
              with:
                name: URRegistryFFI.xcframework.zip
                path: URRegistryFFI.xcframework.zip
            - name: Upload iOS XCFramework to Release
              if: github.ref_type == 'tag'
              uses: svenstaro/upload-release-action@2.5.0
              with:
                file: URRegistryFFI.xcframework.zip
                asset_name: URRegistryFFI.xcframework.zip
                tag: ${{ github.event.base_ref }}
                overwrite: true
                make_latest: false
                body: "iOS XCFramework Checksum $(shasum -a 256 URRegistryFFI.xcframework.zip | cut -b 1-64)"
        
